package com.pojo;

// Generated 27 Nov, 2018 11:28:57 AM by Hibernate Tools 3.4.0.CR1

/**
 * Addressdetails generated by hbm2java
 */
public class Addressdetails implements java.io.Serializable {

	private Integer adid;
	private String fname;
	private String mobileno;
	private String pincode;
	private String apartment;
	private String area;
	private String city;
	private String state;

	public Addressdetails() {
	}

	public Addressdetails(String fname, String mobileno, String pincode, String apartment, String area, String city,
			String state) {
		this.fname = fname;
		this.mobileno = mobileno;
		this.pincode = pincode;
		this.apartment = apartment;
		this.area = area;
		this.city = city;
		this.state = state;
	}

	public Integer getAdid() {
		return this.adid;
	}

	public void setAdid(Integer adid) {
		this.adid = adid;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getMobileno() {
		return this.mobileno;
	}

	public void setMobileno(String mobileno) {
		this.mobileno = mobileno;
	}

	public String getPincode() {
		return this.pincode;
	}

	public void setPincode(String pincode) {
		this.pincode = pincode;
	}

	public String getApartment() {
		return this.apartment;
	}

	public void setApartment(String apartment) {
		this.apartment = apartment;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
