package com.pojo;

// Generated 27 Nov, 2018 11:28:57 AM by Hibernate Tools 3.4.0.CR1

/**
 * Addtocart generated by hbm2java
 */
public class Addtocart implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer customerId;

	public Addtocart() {
	}

	public Addtocart(String name, Integer customerId) {
		this.name = name;
		this.customerId = customerId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

}
