package com.pojo;

// Generated 27 Nov, 2018 11:28:57 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Booktable generated by hbm2java
 */
public class Booktable implements java.io.Serializable {

	private Integer tableid;
	private Registration registration;
	private Date bookingdate;
	private String fromtime;
	private String tofrom;
	private String tablename;

	public Booktable() {
	}

	public Booktable(Registration registration, Date bookingdate, String fromtime, String tofrom, String tablename) {
		this.registration = registration;
		this.bookingdate = bookingdate;
		this.fromtime = fromtime;
		this.tofrom = tofrom;
		this.tablename = tablename;
	}

	public Integer getTableid() {
		return this.tableid;
	}

	public void setTableid(Integer tableid) {
		this.tableid = tableid;
	}

	public Registration getRegistration() {
		return this.registration;
	}

	public void setRegistration(Registration registration) {
		this.registration = registration;
	}

	public Date getBookingdate() {
		return this.bookingdate;
	}

	public void setBookingdate(Date bookingdate) {
		this.bookingdate = bookingdate;
	}

	public String getFromtime() {
		return this.fromtime;
	}

	public void setFromtime(String fromtime) {
		this.fromtime = fromtime;
	}

	public String getTofrom() {
		return this.tofrom;
	}

	public void setTofrom(String tofrom) {
		this.tofrom = tofrom;
	}

	public String getTablename() {
		return this.tablename;
	}

	public void setTablename(String tablename) {
		this.tablename = tablename;
	}

}
