package com.pojo;

// Generated 27 Nov, 2018 11:28:57 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Item generated by hbm2java
 */
public class Item implements java.io.Serializable {

	private Integer id;
	private Addproduct addproduct;
	private Registration registration;
	private Integer iquantity;
	private String status;
	private Set orderstatuses = new HashSet(0);

	public Item() {
	}

	public Item(Addproduct addproduct, Registration registration, Integer iquantity, String status) {
		this.addproduct = addproduct;
		this.registration = registration;
		this.iquantity = iquantity;
		this.status = status;
		this.orderstatuses = orderstatuses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Addproduct getAddproduct() {
		return this.addproduct;
	}

	public void setAddproduct(Addproduct addproduct) {
		this.addproduct = addproduct;
	}

	public Registration getRegistration() {
		return this.registration;
	}

	public void setRegistration(Registration registration) {
		this.registration = registration;
	}

	public Integer getIquantity() {
		return this.iquantity;
	}

	public void setIquantity(Integer iquantity) {
		this.iquantity = iquantity;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set getOrderstatuses() {
		return this.orderstatuses;
	}

	public void setOrderstatuses(Set orderstatuses) {
		this.orderstatuses = orderstatuses;
	}

}
