package com.pojo;

// Generated 27 Nov, 2018 11:28:57 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Mainproduct generated by hbm2java
 */
public class Mainproduct implements java.io.Serializable {

	private Integer mid;
	private String mname;
	private Set specialmenus = new HashSet(0);
	private Set addproducts = new HashSet(0);

	public Mainproduct() {
	}

	public Mainproduct(String mname, Set specialmenus, Set addproducts) {
		this.mname = mname;
		this.specialmenus = specialmenus;
		this.addproducts = addproducts;
	}

	public Integer getMid() {
		return this.mid;
	}

	public void setMid(Integer mid) {
		this.mid = mid;
	}

	public String getMname() {
		return this.mname;
	}

	public void setMname(String mname) {
		this.mname = mname;
	}

	public Set getSpecialmenus() {
		return this.specialmenus;
	}

	public void setSpecialmenus(Set specialmenus) {
		this.specialmenus = specialmenus;
	}

	public Set getAddproducts() {
		return this.addproducts;
	}

	public void setAddproducts(Set addproducts) {
		this.addproducts = addproducts;
	}

}
