package com.pojo;

// Generated 27 Nov, 2018 11:28:57 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Offer generated by hbm2java
 */
public class Offer implements java.io.Serializable {

	private Integer oid;
	private String oname;
	private String image;
	private Date fromdate;
	private Date todate;
	private String oprice;
	private String sprice;

	public Offer() {
	}

	public Offer(String oname, String image, Date fromdate, Date todate, String oprice, String sprice) {
		this.oname = oname;
		this.image = image;
		this.fromdate = fromdate;
		this.todate = todate;
		this.oprice = oprice;
		this.sprice = sprice;
	}

	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	public String getOname() {
		return this.oname;
	}

	public void setOname(String oname) {
		this.oname = oname;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public Date getFromdate() {
		return this.fromdate;
	}

	public void setFromdate(Date fromdate) {
		this.fromdate = fromdate;
	}

	public Date getTodate() {
		return this.todate;
	}

	public void setTodate(Date todate) {
		this.todate = todate;
	}

	public String getOprice() {
		return this.oprice;
	}

	public void setOprice(String oprice) {
		this.oprice = oprice;
	}

	public String getSprice() {
		return this.sprice;
	}

	public void setSprice(String sprice) {
		this.sprice = sprice;
	}

}
