package com.pojo;

// Generated 27 Nov, 2018 11:28:57 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Registration generated by hbm2java
 */
public class Registration implements java.io.Serializable {

	private Integer id;
	private String fname;
	private String lname;
	private String emailid;
	private String username;
	private String password;
	private String address;
	private String mobileno;
	private Set orderstatuses = new HashSet(0);
	private Set booktables = new HashSet(0);
	private Set items = new HashSet(0);

	public Registration() {
	}

	public Registration(String fname, String lname, String emailid, String username, String password, String address,
			String mobileno, Set orderstatuses, Set booktables, Set items) {
		this.fname = fname;
		this.lname = lname;
		this.emailid = emailid;
		this.username = username;
		this.password = password;
		this.address = address;
		this.mobileno = mobileno;
		this.orderstatuses = orderstatuses;
		this.booktables = booktables;
		this.items = items;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	public String getEmailid() {
		return this.emailid;
	}

	public void setEmailid(String emailid) {
		this.emailid = emailid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getMobileno() {
		return this.mobileno;
	}

	public void setMobileno(String mobileno) {
		this.mobileno = mobileno;
	}

	public Set getOrderstatuses() {
		return this.orderstatuses;
	}

	public void setOrderstatuses(Set orderstatuses) {
		this.orderstatuses = orderstatuses;
	}

	public Set getBooktables() {
		return this.booktables;
	}

	public void setBooktables(Set booktables) {
		this.booktables = booktables;
	}

	public Set getItems() {
		return this.items;
	}

	public void setItems(Set items) {
		this.items = items;
	}

}
