package com.pojo;

// Generated 27 Nov, 2018 11:28:57 AM by Hibernate Tools 3.4.0.CR1

/**
 * Specialmenu generated by hbm2java
 */
public class Specialmenu implements java.io.Serializable {

	private Integer id;
	private Mainproduct mainproduct;
	private String sname;
	private String image;
	private String sprice;
	private String squantity;

	public Specialmenu() {
	}

	public Specialmenu(Mainproduct mainproduct, String sname, String image, String sprice, String squantity) {
		this.mainproduct = mainproduct;
		this.sname = sname;
		this.image = image;
		this.sprice = sprice;
		this.squantity = squantity;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Mainproduct getMainproduct() {
		return this.mainproduct;
	}

	public void setMainproduct(Mainproduct mainproduct) {
		this.mainproduct = mainproduct;
	}

	public String getSname() {
		return this.sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public String getSprice() {
		return this.sprice;
	}

	public void setSprice(String sprice) {
		this.sprice = sprice;
	}

	public String getSquantity() {
		return this.squantity;
	}

	public void setSquantity(String squantity) {
		this.squantity = squantity;
	}

}
